apiVersion: kuma.io/v1alpha1
kind: MeshTrafficPermission
metadata:
  name: allow-ui-to-catalog
spec:
  targetRef:
    kind: MeshService
    name: catalog_the-store_svc_80
  from:
    - targetRef:
        kind: MeshService
        name: ui_the-store_svc_80
      default:
        action: Allow
---
apiVersion: kuma.io/v1alpha1
kind: MeshTrafficPermission
metadata:
  name: allow-ui-to-cart
spec:
  targetRef:
    kind: MeshService
    name: cart_the-store_svc_80
  from:
    - targetRef:
        kind: MeshService
        name: ui_the-store_svc_80
      default:
        action: Allow
---
apiVersion: kuma.io/v1alpha1
kind: MeshTrafficPermission
metadata:
  name: allow-cart-to-checkout
spec:
  targetRef:
    kind: MeshService
    name: checkout_the-store_svc_80
  from:
    - targetRef:
        kind: MeshService
        name: cart_the-store_svc_80
      default:
        action: Allow
