_format_version: "3.0"
services:
  - name: the-store-ui
    url: http://the-store-ui.default.svc.cluster.local:80
    routes:
      - name: ui-route
        paths:
          - /
plugins:
  - name: rate-limiting
    config:
      minute: 10
      policy: local

