ingressController:
  enabled: false

proxy:
  type: ClusterIP
  http:
    enabled: true
    servicePort: 80
  tls:
    enabled: false

env:
  database: "off"
  declarative_config: /kong/kong.yaml

extraVolumeMounts:
    - name: kong-config
      mountPath: /kong

extraVolumes:
    - name: kong-config
      configMap:
        name: kong-config